name: Docker Build & Publish

on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Clone My Repository
              uses: actions/checkout@v2

            - name: Login to Docker Hub oooo Cualquier otro Registry
              run: docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASSWORD }}"

            - name: Construir imagen con commit
              run: docker build -t juanfr97/411-music-api:${{ github.sha }} .

            - name: Renombrar la imagen con commit
              run: docker tag juanfr97/411-music-api:${{ github.sha }} juanfr97/411-music-api:latest

            - name: Publicar la imagen
              run: |
                docker push juanfr97/411-music-api:${{ github.sha }}
                docker push juanfr97/411-music-api:latest
    
    migrate-db:
        runs-on: ubuntu-latest
        needs: build-and-push
        steps:
          - name: Login to Docker Hub
            run: docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASSWORD }}"

          - name: Ejecutar migración en producción
            env:
                DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
                DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
                DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
                DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
                DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
            run: |
                docker run --rm \
                    -e DB_HOST=$DB_HOST \
                    -e DB_USER=$DB_USER \
                    -e DB_PASSWORD=$DB_PASSWORD \
                    -e DB_NAME=$DB_NAME \
                    juanfr97/411-music-api:${{ github.sha }} \
                    migrate --yes